#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════════════════
# PULSE Auto-Commit & PR Script
# ══════════════════════════════════════════════════════════════════════════════
#
# For Hermes agents: stage → test → commit → push → PR — all in one command.
#
# Usage:
#   bash scripts/auto_commit.sh "feat: add Bluesky source"
#   bash scripts/auto_commit.sh "fix: handle 429 rate limits" --no-push
#   bash scripts/auto_commit.sh "docs: update README" --no-test
# ══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

# ─── Colors ──────────────────────────────────────────────────────────────────
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

ok()   { echo -e "  ${GREEN}✓${NC} $1"; }
warn() { echo -e "  ${YELLOW}⚠${NC} $1"; }
fail() { echo -e "  ${RED}✗${NC} $1"; exit 1; }

# ─── Args ────────────────────────────────────────────────────────────────────
COMMIT_MSG=""
NO_PUSH=false
NO_TEST=false

for arg in "$@"; do
    case "$arg" in
        --no-push) NO_PUSH=true ;;
        --no-test) NO_TEST=true ;;
        *) COMMIT_MSG="$arg" ;;
    esac
done

if [[ -z "$COMMIT_MSG" ]]; then
    echo "Usage: bash scripts/auto_commit.sh \"commit message\" [--no-push] [--no-test]"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

echo ""
echo -e "${BOLD}PULSE Auto-Commit${NC}"
echo -e "${DIM}Message: $COMMIT_MSG${NC}"
echo ""

# ─── Step 1: Check git status ───────────────────────────────────────────────
echo -e "${BOLD}[1/5] Checking changes...${NC}"

if git diff --quiet && git diff --cached --quiet; then
    warn "No changes to commit"
    exit 0
fi

CHANGED=$(git diff --name-only --cached 2>/dev/null || git diff --name-only)
ok "Changed files: $(echo "$CHANGED" | wc -l | tr -d ' ')"

# ─── Step 2: Run tests ──────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}[2/5] Running tests...${NC}"

if $NO_TEST; then
    warn "Tests skipped (--no-test)"
else
    if python3 tests/test_basic.py 2>/dev/null | grep -q "All tests passed"; then
        ok "All tests passed"
    else
        # Show test output
        python3 tests/test_basic.py
        fail "Tests failed — fix before committing"
    fi
fi

# ─── Step 3: Stage and commit ───────────────────────────────────────────────
echo ""
echo -e "${BOLD}[3/5] Committing...${NC}"

git add -A
ok "Staged all changes"

git commit -m "$COMMIT_MSG" || {
    warn "Nothing to commit"
    exit 0
}
ok "Committed: $(git log -1 --format='%h %s')"

# ─── Step 4: Push ───────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}[4/5] Pushing...${NC}"

if $NO_PUSH; then
    warn "Push skipped (--no-push)"
else
    BRANCH=$(git branch --show-current)
    if git push origin "$BRANCH" 2>/dev/null; then
        ok "Pushed to origin/$BRANCH"
    else
        warn "Push failed (no remote? run: gh repo create pulse --public --source=. --push)"
    fi
fi

# ─── Step 5: Create PR ──────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}[5/5] Pull Request...${NC}"

if $NO_PUSH; then
    warn "PR skipped (--no-push)"
elif command -v gh &>/dev/null; then
    BRANCH=$(git branch --show-current)
    if [[ "$BRANCH" != "main" ]]; then
        # Auto-generate PR body
        PR_BODY="## What Changed
$(git log main..HEAD --oneline | sed 's/^/- /')

## Testing
- [x] Unit tests pass
- [ ] Live tested

---
*Auto-generated by PULSE auto-commit script*"

        if gh pr create \
            --title "$COMMIT_MSG" \
            --body "$PR_BODY" \
            --base main \
            --head "$BRANCH" 2>/dev/null; then
            ok "PR created"
        else
            # Might already exist or other issue
            warn "PR creation skipped (already exists or no remote)"
        fi
    else
        warn "On main branch — create a feature branch for PRs"
    fi
else
    warn "gh CLI not found — install for auto PR creation"
fi

echo ""
echo -e "${GREEN}Done!${NC}"
echo ""
